image: maven:3-jdk-8

cache:
  key: '$CI_COMMIT_REF_NAME'
  paths:
    - .maven/

stages:
  - check
  - test
  - analyze
  - release
  - deploy

before_script:
  - export MAVEN_USER_HOME=`pwd`/.maven

checkstyle:
  stage: check
  script:
    - mvn -ntp site -Dmaven.repo.local=$MAVEN_USER_HOME
  artifacts:
    paths:
      - target/
    expire_in: 1 day

maven-test:
  stage: test
  script:
    - mvn -ntp test -Dmaven.repo.local=$MAVEN_USER_HOME
  artifacts:
    paths:
      - target/
    expire_in: 1 day

maven-jacoco:
  stage: analyze
  script:
    - mvn -ntp jacoco:report -Dmaven.repo.local=$MAVEN_USER_HOME
  artifacts:
    paths:
      - target/
    expire_in: 1 day

maven-pmd:
  stage: analyze
  script:
    - mvn -ntp pmd:pmd -Dmaven.repo.local=$MAVEN_USER_HOME
  artifacts:
    paths:
      - target/
    expire_in: 1 day

maven-package:
  stage: release
  script:
    - mvn -ntp package -DskipTests -Dmaven.repo.local=$MAVEN_USER_HOME
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 day

heroku-deploy:
  stage: deploy
  script:
    - mvn -ntp heroku:deploy -DskipTests -Dmaven.repo.local=$MAVEN_USER_HOME
